apiVersion: v1
kind: Secret
metadata:
  name: omanyte-secret
  labels:
    app: omanyte
stringData:
  auth: {{ required "A valid .Values.omanyte.auth must be specified!" .Values.omanyte.auth | quote }}
