apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: lapras-ingress
spec:
  entryPoints:
    - websecure
  routes:
  {{ if .Values.auth.enabled }}
  - match: Method(`PUT`) && Host(`{{ required "A valid .Values.domain must be specified!" .Values.domain }}`)
    kind: Rule
    services:
      - name: lapras-service
        port: 8080
    middlewares:
      - name: lapras-auth
      - name: security
  {{ end }}
  - match: Host(`{{ required "A valid .Values.domain must be specified!" .Values.domain }}`)
    kind: Rule
    services:
      - name: lapras-service
        port: 8080
    middlewares:
      - name: security
  tls:
    certResolver: tlschallenge
    options:
      name: mytlsoption
      namespace: default
