apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: lapras-ingress
spec:
  entryPoints:
    - websecure
  routes:
  - match: Method(`PUT`) && Host(`{{ required "A valid .Values.domain must be specified!" .Values.domain }}`)
    kind: Rule
    services:
      - name: lapras-service
        port: 8080
    middlewares:
      - name: lapras-auth
  - match: Host(`{{ required "A valid .Values.domain must be specified!" .Values.domain }}`)
    kind: Rule
    services:
      - name: lapras-service
        port: 8080
  tls:
    certResolver: tlschallenge
