{{- if .Values.auth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: lapras-secret
  labels:
    app: lapras
stringData:
  auth: {{ required "A valid .Values.auth.token must be specified!" .Values.auth.token | quote }}
{{- end -}}
