# This exposes the Kubernetes dashboard
dashboard:

  # This is the domain you want to access the dashboard on
  domain: "kubernetes.zuh0.com"

  # This should be the basic authentication secret
  # You can obtain this by using the `htpasswd` command like this
  #   $ htpasswd -nb <username> <password>
  auth:

kubernetes-dashboard:
  protocolHttp: true

  service:
    externalPort: 8080

  ingress:
    enabled: false

  metricsScrapper:
    enabled: true
