{{- if .Values.dashboard.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-secret
  labels:
    app: traefik
stringData:
  auth: {{ required "A valid .Values.dashboard.auth must be specified!" .Values.dashboard.auth | quote }}
{{- end -}}
