apiVersion: apps/v1
kind: Deployment
metadata:
  name: alakazam-deployment
  labels:
    app: alakazam
spec:
  replicas: {{ .Values.alakazam.replicaCount }}
  selector:
    matchLabels:
      app: alakazam
  template:
    metadata:
      labels:
        app: alakazam
    spec:
      initContainers:
      - name: privatebin-volume-permissions
        image: busybox
        command: ['chown', '65534:82', '/mnt']
        securityContext:
          runAsUser: 0
          readOnlyRootFilesystem: True
        volumeMounts:
        - mountPath: "/mnt"
          name: alakazam-data
          readOnly: False
      containers:
      - name: alakazam
        image: privatebin/nginx-fpm-alpine:latest
        env:
        - name: TZ
          value: {{ .Values.alakazam.timezone }}
        - name: PHP_TZ
          value: {{ .Values.alakazam.timezone }}
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: "/srv/data"
            name: alakazam-data
            readOnly: False
        securityContext:
          runAsUser: 65534
          runAsGroup: 82
          readOnlyRootFilesystem: True
      volumes:
      - name: alakazam-data
        hostPath:
          path: /k3svol0/alakazam
          type: DirectoryOrCreate
