apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-dashboard-secret
  labels:
    app: kubernetes-dashboard
stringData:
  auth: {{ required "A valid .Values.dashboard.auth must be specified!" .Values.dashboard.auth | quote }}
